<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findProduitByParametres($data)

    {

        $query = $this->createQueryBuilder('a');
        $query
            ->join('a.categories', 'c')
            ->addSelect('c');
        $query
            ->join('a.tags', 't')
            ->addSelect('t');

        $query->where('a.poids BETWEEN :poidsMin AND :poidsMax')
            ->andWhere('a.prix BETWEEN :prixMin AND :prixMax')
            ->setParameters(array(

                'poidsMin' => $data['poids_Min'],

                'poidsMax' => $data['poids_Max'],

                'prixMin' => $data['prix_Min'],

                'prixMax' => $data['prix_Max']));



        if ($data['categorie'] != '') {
            $cat = $data['categorie'];

            $query->andWhere($query->expr()->in('c.id', $cat));


        }



        if ($data['tag'] != '') {
            $ta = $data['tag'];

            $query->andWhere($query->expr()->in('t.id', $ta));

        }



        if ($data['titre'] != '') {
            $tit = $data['titre'];

            $query->andWhere("a.titre LIKE :titre")
                ->setParameter('titre', '%' . $tit . '%');


        }


        return $query->getQuery()->getResult();

    }


}
